import { useCallback, useEffect, useRef, useState } from 'react';
import { useReducedMotion } from 'framer-motion';
import { Pause, Play, Volume2, VolumeX } from 'lucide-react';
import { cn } from '../lib/cn';

// Version lives in the filename because Vite does not hash assets in public/. Bump it
// when scripts/encode-hero.sh writes a new render, so the immutable cache is bypassed.
// v2 = the race launch, first version with an audio track. v3 = the corrected launch:
// three distinct cars each with their own driver, a Mocaverse crowd, and a stronger score.
const VERSION = 'v3';
const BASE = `/hero/hero.${VERSION}`;

// Ordered by preference — the browser picks the first type it can decode. AV1 is smallest
// and covers most sessions; HEVC exists for Safari, where AV1 decode is the minority
// because Apple ships hardware-only support; H.264 is the floor.
const SOURCES = [
  { src: `${BASE}.av1.webm`, type: 'video/webm; codecs="av01.0.05M.08"' },
  { src: `${BASE}.hevc.mp4`, type: 'video/mp4; codecs="hvc1"' },
  { src: `${BASE}.h264.mp4`, type: 'video/mp4; codecs="avc1.4D401F"' },
];

export const HERO_POSTER = `${BASE}.poster.webp`;

/**
 * Should this visitor download several megabytes of decorative video at all?
 *
 * Answered before anything is fetched, because `<video autoplay>` begins downloading
 * immediately — even offscreen — and would compete with the critical path. On a phone, a
 * metered connection, or with reduced motion requested, the poster alone is the whole
 * experience and not one video byte is spent.
 */
const shouldLoadVideo = () => {
  if (typeof window === 'undefined') return false;

  const connection =
    navigator.connection || navigator.mozConnection || navigator.webkitConnection;
  if (connection) {
    // Explicit signals only. `saveData` is the visitor asking for less data, and a 2g
    // effectiveType is a connection this file genuinely should not spend 3MB on.
    if (connection.saveData) return false;
    if (/(^|-)2g$/.test(connection.effectiveType ?? '')) return false;

    // Deliberately NOT gating on `connection.downlink`. It reads like a bandwidth figure
    // but it is Chrome's Network Quality Estimator: a rolling estimate, quantised and
    // capped for privacy, which falls back to conservative 3g-ish defaults whenever it has
    // few samples to work from. A localhost dev server is exactly that case — measured
    // here it reports effectiveType '3g' / downlink 0.85 / rtt 500 on a fast machine with
    // no network constraint at all. The old `downlink < 1.5` check therefore killed the
    // hero film non-deterministically: identical code, same browser, one load plays and
    // the next shows only the poster, with nothing in the console to explain it.
    // effectiveType above already covers the connections worth protecting, and it is a
    // coarse bucket rather than a number, so it does not flap the same way.
  }

  // Phones get the poster. A 1080p loop is most of a mobile page budget and the hero is
  // mostly covered by type at that width anyway.
  return !window.matchMedia('(max-width: 768px)').matches;
};

/**
 * The hero's background film: real brand artwork, generated by MiniMax and baked at build
 * time (see scripts/gen-video.mjs and scripts/encode-hero.sh) rather than generated per
 * visit — which is what keeps it off the critical path.
 *
 * The poster is deliberately the LCP element. `preload="none"` plus `data-src` on each
 * <source> means the element downloads nothing until we promote the sources by hand, which
 * happens on idle, once the hero is near the viewport, and only if this visitor's device
 * and connection warrant it.
 */
const HeroBackdrop = ({ className, paused = false }) => {
  const videoRef = useRef(null);
  const reduceMotion = useReducedMotion();
  const [armed, setArmed] = useState(false);
  const [playing, setPlaying] = useState(false);
  // Whether *we* paused the film, so a visitor who pressed Pause themselves doesn't get
  // it resumed for them when the overlay above closes (WCAG 2.2.2).
  const suspended = useRef(false);
  // Starts muted and must: autoplay is only permitted for muted media, so sound is strictly
  // opt-in behind a gesture. The track ships inside the video file rather than as a separate
  // <audio> element, which costs ~180KB and buys perfect sync for free.
  const [muted, setMuted] = useState(true);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || reduceMotion || !shouldLoadVideo()) return undefined;

    let cancelled = false;

    const promote = () => {
      if (cancelled) return;
      for (const source of video.querySelectorAll('source[data-src]')) {
        source.src = source.dataset.src;
        source.removeAttribute('data-src');
      }
      video.preload = 'auto';
      video.load();
      setArmed(true);
      // Autoplay can still be refused; the poster stays visible if it is.
      video.play().then(() => setPlaying(true)).catch(() => {});
    };

    const observer = new IntersectionObserver(
      (entries, self) => {
        for (const entry of entries) {
          if (!entry.isIntersecting) continue;
          self.disconnect();
          promote();
        }
      },
      { rootMargin: '200px' },
    );

    // Defer even the observation to idle time so the video can never race the first paint.
    const idle = window.requestIdleCallback
      ? window.requestIdleCallback(() => !cancelled && observer.observe(video), { timeout: 3000 })
      : window.setTimeout(() => !cancelled && observer.observe(video), 1200);

    return () => {
      cancelled = true;
      observer.disconnect();
      if (window.cancelIdleCallback) window.cancelIdleCallback(idle);
      else window.clearTimeout(idle);
    };
  }, [reduceMotion]);

  /**
   * Stop decoding while something opaque covers the hero.
   *
   * Hiding the page behind an overlay doesn't stop a <video>: a 1080p loop keeps burning
   * CPU and battery for as long as the canvas is open, for pixels nobody can see.
   */
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !armed) return;

    if (paused) {
      suspended.current = !video.paused;
      video.pause();
      setPlaying(false);
    } else if (suspended.current) {
      suspended.current = false;
      video.play().then(() => setPlaying(true)).catch(() => {});
    }
  }, [paused, armed]);

  const toggle = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) video.play().then(() => setPlaying(true)).catch(() => {});
    else {
      video.pause();
      setPlaying(false);
    }
  }, []);

  /**
   * Set `muted` on the element, not through React. React's `muted` prop does not reliably
   * reflect to the attribute, and getting this wrong means either no autoplay or no sound.
   * Unmuting also resumes playback, because being handed silence on a paused video is a
   * confusing answer to clicking "Sound".
   */
  const toggleSound = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    const next = !video.muted;
    video.muted = next;
    setMuted(next);
    if (!next && video.paused) video.play().then(() => setPlaying(true)).catch(() => {});
  }, []);

  return (
    // No aria-hidden on this wrapper: the pause control below has to stay in the
    // accessibility tree and the tab order. Only the decorative media is hidden.
    <div className={cn('pointer-events-none absolute inset-0 overflow-hidden', className)}>
      <video
        ref={videoRef}
        aria-hidden="true"
        poster={HERO_POSTER}
        autoPlay
        muted
        loop
        playsInline
        preload="none"
        disablePictureInPicture
        tabIndex={-1}
        width={1920}
        height={1080}
        className="h-full w-full object-cover"
        // Explicit ratio + object-cover means the box never resizes when the video
        // arrives, so swapping poster for film costs no layout shift.
        style={{ aspectRatio: '16 / 9' }}
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        // Keeps the label honest if anything other than our button changes the mute state.
        onVolumeChange={(event) => setMuted(event.currentTarget.muted)}
      >
        {SOURCES.map(({ src, type }) => (
          <source key={src} data-src={src} type={type} />
        ))}
      </video>

      {/* Scrim, deliberately lighter than it was.
          v1 was tuned for a montage that swung from bright white studio shots to near-black
          violet, so it had to hold the worst case: 0.55 flat plus a 0.62 radial worked out to
          ~0.83 of darkening dead centre, which buried the film. From v2 on it is a single
          night-graded film that is already dark and high-contrast, so the floor can come up a
          long way. Now ~0.66 at centre.

          The vertical ramp is explicit stops rather than Tailwind's three-stop gradient so the
          opening can be held back through the top three quarters while the very bottom edge
          still reaches full opacity — that last part is load-bearing, it is what makes the
          section blend into the page below instead of ending on a seam. */}
      {/* The violet grade is carried by the two scrims below and nothing else.
          There is deliberately NO `mix-blend-mode` layer over the video. A `screen` layer
          is the textbook way to lift crushed blacks toward a hue, and it read well — but
          mix-blend-mode over a <video> is a known compositing hazard (Safari especially
          can drop the video to a static frame or blank once it is promoted to its own
          layer), and a decorative grade is not worth risking the hero on.
          It is also close to redundant: these scrims are semi-transparent violet-black
          over dark footage, which already raises the black floor toward violet. What a
          blend layer would add over that is small.
          The film is near-achromatic (its darks measure #0B0E10 / #374448, around hue 200
          at almost no chroma), so the two obvious alternatives are both dead ends:
          hue-rotate scales chroma that isn't there, and a saturated purple wash at hue 302
          partially cancels against the cool cast and reads as mud. The proper fix is to
          grade it at encode time in scripts/encode-hero.sh (a colorbalance shadow lift on
          a v4 render, poster re-rendered from the same chain) — zero runtime cost and no
          blend-mode risk at all. */}
      <div
        className="absolute inset-0"
        style={{
          background:
            'linear-gradient(to bottom, rgb(var(--ground-rgb) / 0.42) 0%, rgb(var(--ground-rgb) / 0.38) 45%, rgb(var(--ground-rgb) / 0.74) 78%, rgb(var(--ground-rgb) / 1) 100%)',
        }}
      />
      <div
        className="absolute inset-0"
        style={{
          background:
            'radial-gradient(60% 55% at 50% 42%, rgb(var(--ground-rgb) / 0.45) 0%, rgb(var(--ground-rgb) / 0.18) 60%, transparent 100%)',
        }}
      />

      {/* WCAG 2.2.2 (Pause, Stop, Hide): motion that runs longer than five seconds needs a
          control available to everyone, not only to visitors who set the OS reduce-motion
          flag. Rendered only once the film is actually running, so it never offers to
          pause a still poster. */}
      {armed && (
        <div className="pointer-events-auto absolute bottom-4 right-4 z-10 flex items-center gap-2">
          {/* data-hero-control, not a class, is what scripts/verify-hero.mjs asserts on. It
              used to look for `button[class*="bottom-4"]`, which silently stopped matching the
              moment these were wrapped in a positioned container. */}
          <button
            type="button"
            data-hero-control="sound"
            onClick={toggleSound}
            aria-pressed={!muted}
            className="flex items-center gap-1.5 rounded-full border border-white/15 bg-slate-950/60 px-3 py-1.5 text-xs font-medium text-slate-300 backdrop-blur-md transition-colors hover:text-white"
          >
            {muted ? <VolumeX className="h-3 w-3" /> : <Volume2 className="h-3 w-3" />}
            {muted ? 'Sound' : 'Mute'}
            <span className="sr-only"> for the background film</span>
          </button>
          <button
            type="button"
            data-hero-control="playback"
            onClick={toggle}
            className="flex items-center gap-1.5 rounded-full border border-white/15 bg-slate-950/60 px-3 py-1.5 text-xs font-medium text-slate-300 backdrop-blur-md transition-colors hover:text-white"
          >
            {playing ? <Pause className="h-3 w-3" /> : <Play className="h-3 w-3" />}
            {playing ? 'Pause' : 'Play'}
            <span className="sr-only"> background video</span>
          </button>
        </div>
      )}
    </div>
  );
};

export default HeroBackdrop;
