#!/usr/bin/env node
// Put a mesh that already exists into the pipeline, without paying to make it again.
//
// WHY THIS EXISTS. Several meshes in assets/probes/ were generated by hand during round 9 and are
// better than what a fresh pipeline run would produce — the adidas ape's best mesh came from a
// frame of its own film, which the pipeline does not yet know how to do. Regenerating those to get
// them into R2 would be paying twice for a worse result.
//
// It writes the same record shape worker/mesh.js writes, plus an `importedFrom` note, because an
// asset whose provenance says "generated by the pipeline from the still" when it was not is a lie
// that would be very hard to catch later.
//
//   node scripts/import-mesh.mjs <assetKey> <file.glb> "<how it was made>" [--inference low|high]
//   node scripts/import-mesh.mjs --list

import { execFileSync } from 'node:child_process';
import { statSync } from 'node:fs';

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const at = argv.indexOf(`--${name}`);
  return at === -1 ? fallback : argv[at + 1];
};

const BUCKET = 'nft-video-gen-storyboards';
const MESH_VERSION = 1;
const positional = argv.filter((a) => !a.startsWith('--') && argv[argv.indexOf(a) - 1]?.startsWith('--') !== true);

if (argv.includes('--list')) {
  const out = execFileSync('npx', ['wrangler', 'kv', 'key', 'list', '--binding', 'DOSSIERS', '--local'], {
    encoding: 'utf8', maxBuffer: 64 * 1024 * 1024,
  });
  for (const { name } of JSON.parse(out.slice(out.indexOf('[')))) {
    if (name.startsWith('castmesh:')) console.log(name);
  }
  process.exit(0);
}

const [assetKey, file, provenance] = positional;
if (!assetKey || !file || !provenance) {
  console.error('Usage: import-mesh.mjs <assetKey> <file.glb> "<how it was made>" [--inference low|high]');
  process.exit(1);
}

const bytes = statSync(file).size;
const r2Key = `${'cast'}/${assetKey}/v${MESH_VERSION}/mesh.glb`;

// The dossier is the source of truth for what the piece IS; the import only supplies the geometry.
const dossierRaw = execFileSync('npx', ['wrangler', 'kv', 'key', 'get', `dossier:v5:${assetKey}`, '--binding', 'DOSSIERS', '--local'], {
  encoding: 'utf8', maxBuffer: 8 * 1024 * 1024,
});
const dossier = JSON.parse(dossierRaw.slice(dossierRaw.indexOf('{')));

const record = {
  assetKey,
  meshVersion: MESH_VERSION,
  medium: dossier.medium ?? null,
  status: 'ready',
  representation: 'blocking-proxy',
  inference: flag('inference', ['3d-render', 'photoreal'].includes(dossier.medium) ? 'low' : 'high'),
  caveat: null,
  r2Key,
  bytes,
  // NOT assumed. Several probe meshes predate the face_limit decision and are 4x heavier than
  // anything the pipeline produces now; recording a limit they were not generated under would
  // misdescribe them exactly as claiming pipeline provenance would.
  faceLimit: Number(flag('face-limit', 0)) || null,
  sourceUrl: dossier.sourceImageUrls?.[0] ?? null,
  model: 'tripo3d/image_to_model',
  // NOT "the pipeline made this from the still", because it did not. An asset that misdescribes
  // how it was made is worse than one with no description at all.
  importedFrom: { file, provenance, importedAt: Date.now() },
  createdAt: Date.now(),
  readyAt: Date.now(),
};

execFileSync('npx', ['wrangler', 'r2', 'object', 'put', `${BUCKET}/${r2Key}`, '--file', file, '--content-type', 'model/gltf-binary', '--local'], { stdio: 'inherit' });
execFileSync('npx', ['wrangler', 'kv', 'key', 'put', `castmesh:v${MESH_VERSION}:${assetKey}`, JSON.stringify(record), '--binding', 'DOSSIERS', '--local'], { stdio: 'inherit' });

console.log(`\n✔ ${assetKey}`);
console.log(`  ${(bytes / 1048576).toFixed(2)} MB  inference=${record.inference}  medium=${record.medium}  faceLimit=${record.faceLimit ?? 'unset (default, heavy)'}`);
if (bytes > 6 * 1048576) {
  console.log('  ⚠ over 6MB. The pipeline generates ~3.7MB at face_limit 30000; this one predates that.');
}
console.log(`  provenance: ${provenance}`);
