#!/usr/bin/env node
// Put a mesh that already exists into the pipeline, without paying to make it again.
//
// WHY THIS EXISTS. Several meshes in assets/probes/ were generated by hand during round 9 and are
// better than what a fresh pipeline run would produce — the adidas ape's best mesh came from a
// frame of its own film, which the pipeline does not yet know how to do. Regenerating those to get
// them into R2 would be paying twice for a worse result.
//
// It writes the same record shape worker/mesh.js writes, plus an `importedFrom` note, because an
// asset whose provenance says "generated by the pipeline from the still" when it was not is a lie
// that would be very hard to catch later.
//
// LOCAL BY DEFAULT, and `--remote` is what puts a mesh in front of actual visitors. Until that
// flag existed every call here was hardcoded `--local`, so an imported mesh could not reach
// production at all — which is not a thing anyone would guess from the outside: the storyboard
// simply drew proxy boxes, exactly as it does for a piece that has no mesh, with nothing anywhere
// to say the geometry existed but was in the wrong store.
//
//   node scripts/import-mesh.mjs <assetKey> <file.glb> "<how it was made>" [--inference low|high]
//   node scripts/import-mesh.mjs <assetKey> <file.glb> "<how it was made>" --remote
//   node scripts/import-mesh.mjs --list [--remote]

import { execFileSync } from 'node:child_process';
import { statSync } from 'node:fs';

const argv = process.argv.slice(2);

// Flags that CONSUME the next argument. Needed so the positional parser can tell
// `--inference low` (two tokens, one flag) from `--remote key.glb` (a flag and a positional).
// The old parser dropped any argument that merely followed a flag, which was harmless while every
// flag took a value and silently ate the first positional the moment a boolean one was added.
const VALUE_FLAGS = new Set(['--inference', '--face-limit']);

const flag = (name, fallback) => {
  const at = argv.indexOf(`--${name}`);
  return at === -1 ? fallback : argv[at + 1];
};

const positional = [];
for (let i = 0; i < argv.length; i += 1) {
  if (argv[i].startsWith('--')) {
    if (VALUE_FLAGS.has(argv[i])) i += 1;
    continue;
  }
  positional.push(argv[i]);
}

const BUCKET = 'nft-video-gen-storyboards';
const MESH_VERSION = 1;
const REMOTE = argv.includes('--remote');
const STORE = REMOTE ? '--remote' : '--local';

if (argv.includes('--list')) {
  const out = execFileSync('npx', ['wrangler', 'kv', 'key', 'list', '--binding', 'DOSSIERS', STORE], {
    encoding: 'utf8', maxBuffer: 64 * 1024 * 1024,
  });
  for (const { name } of JSON.parse(out.slice(out.indexOf('[')))) {
    if (name.startsWith('castmesh:')) console.log(name);
  }
  process.exit(0);
}

const [assetKey, file, provenance] = positional;
if (!assetKey || !file || !provenance) {
  console.error('Usage: import-mesh.mjs <assetKey> <file.glb> "<how it was made>" [--inference low|high] [--remote]');
  process.exit(1);
}

console.log(`Importing into ${REMOTE ? 'PRODUCTION (remote R2 + KV)' : 'the local dev store'}.\n`);

const bytes = statSync(file).size;
const r2Key = `${'cast'}/${assetKey}/v${MESH_VERSION}/mesh.glb`;

// The dossier is the source of truth for what the piece IS; the import only supplies the geometry.
// Read from the SAME store being written to. A record built from the local dossier and written to
// production would describe the piece by whatever this machine happened to know about it.
let dossier;
try {
  const dossierRaw = execFileSync('npx', ['wrangler', 'kv', 'key', 'get', `dossier:v5:${assetKey}`, '--binding', 'DOSSIERS', STORE], {
    encoding: 'utf8', maxBuffer: 8 * 1024 * 1024,
  });
  dossier = JSON.parse(dossierRaw.slice(dossierRaw.indexOf('{')));
} catch {
  console.error(`No v5 dossier for ${assetKey} in the ${REMOTE ? 'remote' : 'local'} store.`);
  console.error('Cast the piece there first — the dossier is what says what this thing IS, and a');
  console.error('mesh record built without it would carry no medium, no inference and no source.');
  process.exit(1);
}

const record = {
  assetKey,
  meshVersion: MESH_VERSION,
  medium: dossier.medium ?? null,
  status: 'ready',
  representation: 'blocking-proxy',
  inference: flag('inference', ['3d-render', 'photoreal'].includes(dossier.medium) ? 'low' : 'high'),
  caveat: null,
  r2Key,
  bytes,
  // NOT assumed. Several probe meshes predate the face_limit decision and are 4x heavier than
  // anything the pipeline produces now; recording a limit they were not generated under would
  // misdescribe them exactly as claiming pipeline provenance would.
  faceLimit: Number(flag('face-limit', 0)) || null,
  sourceUrl: dossier.sourceImageUrls?.[0] ?? null,
  model: 'tripo3d/image_to_model',
  // NOT "the pipeline made this from the still", because it did not. An asset that misdescribes
  // how it was made is worse than one with no description at all.
  importedFrom: { file, provenance, importedAt: Date.now() },
  createdAt: Date.now(),
  readyAt: Date.now(),
};

// BYTES BEFORE RECORD, and the order is load-bearing. The record is what /api/cast/mesh trusts to
// decide the mesh is servable; writing it first opens a window where the endpoint promises a GLB
// that R2 cannot yet produce. Written this way round, the worst case is bytes nobody reads yet.
execFileSync('npx', ['wrangler', 'r2', 'object', 'put', `${BUCKET}/${r2Key}`, '--file', file, '--content-type', 'model/gltf-binary', STORE], { stdio: 'inherit' });
execFileSync('npx', ['wrangler', 'kv', 'key', 'put', `castmesh:v${MESH_VERSION}:${assetKey}`, JSON.stringify(record), '--binding', 'DOSSIERS', STORE], { stdio: 'inherit' });

console.log(`\n✔ ${assetKey}  →  ${REMOTE ? 'production' : 'local'}`);
console.log(`  ${(bytes / 1048576).toFixed(2)} MB  inference=${record.inference}  medium=${record.medium}  faceLimit=${record.faceLimit ?? 'unset (default, heavy)'}`);
if (bytes > 6 * 1048576) {
  console.log('  ⚠ over 6MB. The pipeline generates ~3.7MB at face_limit 30000; this one predates that.');
}
console.log(`  provenance: ${provenance}`);
